### PR TITLE
Update test_button.py closes #13

### LINKED ISSUE #13: (PYL-E0102) Function or method is being redefined
## Description
A function, method or class is being redefined in the same scope. This would override the original definition, and doing this is strongly discouraged. Please verify that this is something that you intended to do.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/torrua/keyboa/issue/PYL-E0102/occurrences/](https://deepsource.io/gh/torrua/keyboa/issue/PYL-E0102/occurrences/)

### PR DESCRIPTION
**Pull request by umairkarel**
```diff
-def test_acceptable_button_source_types(button_data):
+def test_acceptable_button_source_types_without_callback(button_data):
```

### CODE REVIEW

**Comment by torrua** [comment]
Can you please rename it to `test_unacceptable_button_source_types_without_callback`? 😉

**Comment by umairkarel** [comment]
> Can you please rename it to `test_unacceptable_button_source_types_without_callback`? 😉

I've already done that!

**Comment by torrua** [comment]
Our function names are slightly different, as you can see. 🙄

**Comment by umairkarel** [comment]
> Our function names are slightly different, as you can see. 🙄

Done!

**Comment by umairkarel** [comment]
> Our function names are slightly different, as you can see. 🙄

Done!

**Pull request merged**
